image: java:8-jdk

stages:
- build
- test

before_script:
- echo "Start Continuous IntegrationI"

cache:
  paths:
  - .gradle/wrapper
  - .gradle/caches

build:
  stage: build
  script:
  - ./gradlew assemble
  artifacts:
    paths:
    - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
  - ./gradlew check

#deploy:
#  stage: deploy
#  script:
#    - ./deploy

after_script:
- echo "End Continuous Integration"